import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { BooksProvider } from '../books/BooksProvider'
import { Books } from '../books/Books'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <BooksProvider>
          <Books />
        </BooksProvider>
      </main>

    </div>
  )
}

export default Home
